# This file was generated automatically from conda-smithy. To update this configuration,
# update the conda-forge.yml and/or the recipe/meta.yaml.

language: generic

os: osx
osx_image: xcode6.4

env:
  matrix:
    - CONFIG=osx_r_base3.4.1target_platformosx-64
    - CONFIG=osx_r_base3.5.1target_platformosx-64

  global:
    # The BINSTAR_TOKEN secure variable. This is defined canonically in conda-forge.yml.
    - secure: "eoyNvwSNqxBATZLk9ZujqGebWGXcslz2Q83P105d3l7lt2gnc/zzB77wf/Q1Pe3PZSx9LcAEmsDF0vREzb1HtiqeXCU78KsNHNZKDd9vfmpVVt1C83IRMhIB8uxC0d0CAe53lxlOcH70mcX6N40Mf5PUqT7GXPny8+RyWGI2RbZRvNb6jSdo9CoAvTUxunb6wzZfMaywuEYgrAdOJv55PpKB8egkzvn7tr6VX8wcQSQ9e7fOy/2LhZIXbFWpwiRIwKub+4R84ET3KTMib+S4+cdOYDVbLX8DeAdQLXfxMKy41gcMsDL01Yn2nHo82oZK0YuERhGQiMHnCT2FzYYoDLmHiQ4/KBocfPxh+W5SDtvrGuwyp0H+9ibcH6+kz9kKADIJFFShtZqyqqdszaLDiq+Y8tBZ4ab6si1gfWdzPts2mOX3Y2aqOPqfg0XTfdlWImaFtKW0XxM9rNu8IQmthtx+dytU7xHoWEbEsWsg36d/+YyICSQtitYEgT26zmb/2GhPOyIxiYpD4BPesXjlm/2methJ/2mw2Fn9mZqQs2/A4BNHZXsTUGLo7h4HTKHpTFyLCIPwPDCLjlb7eH2T4zTr8n+vSkqNIf428x+IWqRFEXm577Xhn0tiZOJbAtmJYXxO1b9RX+mbKqDP7fwXR6TZfqcu9Wa6RaDJ9+LnceU="


before_install:
    # Fast finish the PR.
    - |
      (curl https://raw.githubusercontent.com/conda-forge/conda-forge-ci-setup-feedstock/branch2.0/recipe/conda_forge_ci_setup/ff_ci_pr_build.py | \
          python - -v --ci "travis" "${TRAVIS_REPO_SLUG}" "${TRAVIS_BUILD_NUMBER}" "${TRAVIS_PULL_REQUEST}") || exit 1

    # Remove homebrew.
    - |
      echo ""
      echo "Removing homebrew from Travis CI to avoid conflicts."
      curl -fsSL https://raw.githubusercontent.com/Homebrew/install/master/uninstall > ~/uninstall_homebrew
      chmod +x ~/uninstall_homebrew
      ~/uninstall_homebrew -fq
      rm ~/uninstall_homebrew


install:
    # Install Miniconda.
    - |
      echo ""
      echo "Installing a fresh version of Miniconda."
      MINICONDA_URL="https://repo.continuum.io/miniconda"
      MINICONDA_FILE="Miniconda3-latest-MacOSX-x86_64.sh"
      curl -L -O "${MINICONDA_URL}/${MINICONDA_FILE}"
      bash $MINICONDA_FILE -b

    # Configure conda.
    - |
      echo ""
      echo "Configuring conda."
      source /Users/travis/miniconda3/bin/activate root

      conda install --yes --quiet conda-forge::conda-forge-ci-setup=2
      setup_conda_rc ./ ./recipe ./.ci_support/${CONFIG}.yaml

      source run_conda_forge_build_setup

    # compiler cleanup
    - |
      mangle_compiler ./ ./recipe ./.ci_support/${CONFIG}.yaml

script:
  # generate the build number clobber
  - make_build_number ./ ./recipe ./.ci_support/${CONFIG}.yaml
  - conda build ./recipe -m ./.ci_support/${CONFIG}.yaml --clobber-file ./.ci_support/clobber_${CONFIG}.yaml
  - upload_package ./ ./recipe ./.ci_support/${CONFIG}.yaml
