travis:
  secure:
    BINSTAR_TOKEN: YJG4S5CwxPj3vz2D/aRggwfdXh/7FsU5ejBRfqXV1PzeAH9WUAM5xG/puhP+4AzbuA+ev/ES3mkpNm4y7S612+F1ywvW50n5c4Cg2jGvRJFi3o7lGrTli0rNWlS4sA7FnEb+CjBdQW85Wa0qzRB10MbYeVi/xyuq0pMYbXUCqFYKSNI+WcyOk8m23/zLc9QNFDFYFPWZlUton/s1cYbOLwAZSAOEmaZLjr2iiAsEkTFXjiErTA4z4TCYeYicNBG1giDY+23GGFnpmbxf6uQ8ACoEYfH2VwZoIoZX2dfiEVEcj+jFOrP5+NkvlL0HqhRvQ7jyASzIrqKbqlajaTj1ZKF+BIuOfYKSg4NYXLXdQyCD0spK97zUtz1GDpctOvanM4tW1A0NDv1NrjYYf2ka6N/lvyi5kasFWzJiE2SCBHTUVaYPm3CiP+oOI+uFu97CGse6uHdGFq7xTSKkfRoUn0zEVfUshLeKTRQ0DQECDnZiGIQTUEucNn0LP6IOqd+UJzNis85qA2w8URkNEjUR/fTimI86n4q+H/ONdfgWJ5lxVVS1XD8z93jzOojSRIPPwrNMCtzwXyKDqnWOXTuzxCH3halS4op2R0K60TO8XnE6wXwEvv45qmTnDA3kHXPEYGwRGDmMOHP1j+tvl7XQ9l8OUo1z1gFdKq3Az9RNQsA=
appveyor:
  secure:
    BINSTAR_TOKEN: ipv/06DzgA7pzz2CIAtbPxZSsphDtF+JFyoWRnXkn3O8j7oRe3rzqj3LOoq2DZp4
conda_forge_output_validation: true
